### ISSUE TITLE
[feat] support kibana space & role

### ISSUE THREAD

**Issue by Wing924** [ewilde/terraform-provider-kibana#29]
# WHAT

Please support kibana space & role API
https://www.elastic.co/guide/en/kibana/7.4/spaces-api.html
https://www.elastic.co/guide/en/kibana/7.4/role-management-api.html

# WHY

kibana space is very useful for multi-tenant.

**Comment by ewilde** [comment]
@jfroche has PR for this #28 #30

**Comment by ewilde** [comment]
Closed via #28 #30
