### ISSUE TITLE
terraform 0.12.xx support?

### ISSUE THREAD

**Issue by avishnyakov** [ewilde/terraform-provider-kibana#31]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.10

### Affected Resource(s)
kibana plugin

### Terraform Configuration Files
Basic example from the https://github.com/ewilde/terraform-provider-kibana/tree/master/examples

```hcl
provider "kibana" {
}

data "kibana_index" "main" {
  filter = {
    name = "title"
    values = ["logstash-*"]
  }
}

resource "kibana_search" "china" {
  name 	        = "Chinese origin - errors"
  description     = "Errors occured when source was from china"
  display_columns = ["_source"]
  sort_by_columns = ["@timestamp"]
  search = {
    index   = "${data.kibana_index.main.id}"
    filters = [
      {
        match = {
          field_name = "geo.src"
          query      = "CN"
          type       = "phrase"
        },
      },
      {
        match = {
          field_name = "@tags"
          query      = "error"
          type       = "phrase"
        }
      }
    ]
  }
}
```

### Debug Output
https://gist.github.com/avishnyakov/2832b998fc7077a155df38754bea4de6

### Expected Behavior
It should work with terraform 0.12.xx

### Actual Behavior
It does not work with terraform 0.12.xx

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  use any of configs in Basic example from the https://github.com/ewilde/terraform-provider-kibana/tree/master/examples
2.  `terraform plan`

Failing: 
> Error: Failed to instantiate provider "kibana" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### Important Factoids
N/A

### References
N/A

**Comment by devenney** [comment]
This is resolved in v0.7.0. Let me know if you experience any issues.
