### ISSUE TITLE
Elastic/Kibana 7.4.0 support: /api/saved_objects/_find and spaces

### ISSUE THREAD

**Issue by avishnyakov** [ewilde/terraform-provider-kibana#32]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.10.8

### Affected Resource(s)
* kibana_index 
* probably others due to changes api endpoints and/or Kibana spaces support

### Terraform Configuration Files
Basic example from the https://github.com/ewilde/terraform-provider-kibana/tree/master/examples

```hcl
provider "kibana" {
}

data "kibana_index" "main" {
  filter = {
    name = "title"
    values = ["logstash-*"]
  }
}

resource "kibana_search" "china" {
  name 	        = "Chinese origin - errors"
  description     = "Errors occured when source was from china"
  display_columns = ["_source"]
  sort_by_columns = ["@timestamp"]
  search = {
    index   = "${data.kibana_index.main.id}"
    filters = [
      {
        match = {
          field_name = "geo.src"
          query      = "CN"
          type       = "phrase"
        },
      },
      {
        match = {
          field_name = "@tags"
          query      = "error"
          type       = "phrase"
        }
      }
    ]
  }
}
```

### Debug Output
https://gist.github.com/avishnyakov/69179f26c2fc870f03c4dd39f88d4730

### Expected Behavior
It should work with Elastic/Kibana 7.4.0 

### Actual Behavior
It does not work with  Elastic/Kibana 7.4.0 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  use any of configs in Basic example from the https://github.com/ewilde/terraform-provider-kibana/tree/master/examples
2.  `terraform plan`

Failing: 
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.kibana_index.filebeat: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.kibana_index.filebeat: 1 error(s) occurred:

* data.kibana_index.filebeat: data.kibana_index.filebeat: Status: 404, {"statusCode":404,"error":"Not Found","message":"Not Found"}
```

### Important Factoids
1) https://www.elastic.co/guide/en/kibana/master/saved-objects-api-find.html seems to be changed, the endpoint is `/api/saved_objects/_find` but kibana plugin hits `/api/saved_objects?fields=title&fields=timeFieldName&fields=fields&per_page=100&type=index-pattern`

Using _find endpoint like this solve the problem  `/api/saved_objects/_find?fields=title&fields=timeFieldName&fields=fields&per_page=100&type=index-pattern`

2) Support kibana spaces, new find object API support spaces:
`GET /s/<space_id>/api/saved_objects/_find` 
> https://www.elastic.co/guide/en/kibana/master/saved-objects-api-find.html

### References
* https://www.elastic.co/guide/en/kibana/master/saved-objects-api-find.html

**Comment by avishnyakov** [comment]
Oh, turned out that kibana provider has `kibana_version` property which then re-points api calls to the right endpoint in kibana package. Brilliant! Closing this one, kibana spaces should probably go into separate issue.

```
provider "kibana" {
  # ...
  kibana_version = "7.4.0"
}
```

**Comment by lllama** [comment]
@avishnyakov Did you manage to get this working? I'm running 7.4.0 and keep getting 404 errors whenever I run `plan` or `refresh`. (I don't see 7.4.x listed in the supported versions.)
