### ISSUE TITLE
Logzio Kibana 7

### ISSUE THREAD

**Issue by michalschott** [ewilde/terraform-provider-kibana#37]
Got this email yesterday from logzio team:

```
We are happy to inform you that we are upgrading our user interface to Kibana 7! 
In addition to a significant performance boost, Kibana 7 offers users a new time picker, new filtering, a better dashboarding experience, and overall -- a much nicer look and feel. 
We will gradually be rolling out this upgrade in the upcoming few weeks and will provide more detailed information on our blog. In the meantime, if you have any questions whatsoever, please feel free to reach out to our Support team.
Enjoy!
```

Wonder if provider will work out of the box?

**Comment by ewilde** [comment]
@devenney do you know if this works on Logz.io now we are on 7?

**Comment by devenney** [comment]
@ewilde It looks like none of our estate has been hit by the rollout yet. We test support for `logz.io` and `7.3.X` separately so it should be as simple as the end-user bumping `kibana_version`.

We will, of course, need to keep an eye out and bump the `kibana_version` used for our CI once Logz upgrade our estate. That will tell us for sure if there are any breakages - it's always possible they go to a minor version which messes with some of our functionality.

**Comment by michalschott** [comment]
Hey.

We just got sneaky update today resulting in ```	* kibana_search.environment_frontend_filter: failed to create kibana saved search: &{0xc0007c0fc0} error: POST API call to https://app-eu.logz.io/api/saved_objects/search?overwrite=true failed 409 Conflict. Code: 409, Body: {"statusCode":409,"error":"Conflict","message":"refresh kibana"}, Message: Could not create search```

**Comment by michalschott** [comment]
Hi again,

after upgrading `kibana_version` to `7.2.1` and restoring previously know terraform state, I was able to use this provider again.

Their UI bugs in visualizations is another good story...

**Comment by michalschott** [comment]
Closing in favor of https://github.com/ewilde/terraform-provider-kibana/issues/42
