### ISSUE TITLE
Vizualization KO with kibana 7.3.1

### ISSUE THREAD

**Issue by lucaspouzac** [ewilde/terraform-provider-kibana#38]
Hello, 

I try this provider for create Search and Vizualize. 

Search creation is OK, but Vizualize is KO. It's impossible to open it in kibana after creation. I think that a field **savedSearchRefName** is missing

WHen I create the vizualization manually, this filed is present.

![image](https://user-images.githubusercontent.com/758899/69816541-e5039400-11f8-11ea-9a4e-5428a8fd5a70.png)

**Comment by ewilde** [comment]
closed by: https://github.com/ewilde/terraform-provider-kibana/pull/39
