### ISSUE TITLE
Publish on Terraform registry?

### ISSUE THREAD

**Issue by ottramst** [ewilde/terraform-provider-kibana#53]
Hi!

Thanks for the hard work with the provider!
Are there any plans publishing the provider to Terraform Registry?

Thanks!

**Comment by ewilde** [comment]
@ottramst thank you for the suggestion. I will begin working on this following the steps in :

https://www.terraform.io/docs/registry/providers/publishing.html?_ga=2.152396476.444474353.1610356844-1973112316.1605263356

**Comment by miguelnge** [comment]
Hi @ewilde , I'm wondering if you had the time to publish this plugin to the Terraform registry. Currently, we're using TF >0.13 and the only way we found to make it work was to generate a local filesystem mirror to publish the built plugin. This would help us to simplify the process.

**Comment by ewilde** [comment]
👋 hey @miguelnge thank you for your comment, i'm planning to get this published over the weekend and will ping this thread with an update.

**Comment by ewilde** [comment]
🎉 got this published now

https://registry.terraform.io/providers/ewilde/kibana/latest

![image](https://user-images.githubusercontent.com/329397/107270570-05f18700-6a43-11eb-850e-d84287c71cfd.png)

Please feel free to re-open the issue if something is missing
