### ISSUE TITLE
404 with 6.3.1 kibana

### ISSUE THREAD

**Issue by dzinevich** [ewilde/terraform-provider-kibana#7]
Hello,
when running plan on 6.3.1 Kibana I'm getting 404
if I check logs, I see following in access log:
`/_plugin/kibana/api/saved_objects/?fields=title&fields=timeFieldName&fields=fields&per_page=100&type=index-pattern`

should be with /_find? (see https://www.elastic.co/guide/en/kibana/master/saved-objects-api-find.html)
I tried adding "/_find" in vendor/github.com/ewilde/go-kibana/saved_objects.go, however for some reason this has no effect...
`func (api *savedObjectsClient600) GetByType(request *SavedObjectRequest) (*SavedObjectResponse, error) {
        address, err := addQueryString(api.config.KibanaBaseUri+savedObjectsPath+"_find", request)`
I'm far from being go developer, so may be I missed something.

**Comment by ewilde** [comment]
@malmon @dzinevich this has now been fixed and released https://github.com/ewilde/terraform-provider-kibana/releases/tag/v0.6.1
